.. toctree::
    :maxdepth: 1

    /reference/parameter_types/boolean
    /reference/parameter_types/compound_boolean
    /reference/parameter_types/choice
    /reference/parameter_types/datetime
    /reference/parameter_types/email
    /reference/parameter_types/html
    /reference/parameter_types/identifier
    /reference/parameter_types/integer
    /reference/parameter_types/item_link
    /reference/parameter_types/link
    /reference/parameter_types/number
    /reference/parameter_types/range
    /reference/parameter_types/text_line
    /reference/parameter_types/text
    /reference/parameter_types/url
    /reference/parameter_types/ez_content_type
    /reference/parameter_types/ezlocation
    /reference/parameter_types/ezcontent
    /reference/parameter_types/eztags
