* :doc:`/reference/parameter_types/boolean`
* :doc:`/reference/parameter_types/compound_boolean`
* :doc:`/reference/parameter_types/choice`
* :doc:`/reference/parameter_types/email`
* :doc:`/reference/parameter_types/html`
* :doc:`/reference/parameter_types/identifier`
* :doc:`/reference/parameter_types/integer`
* :doc:`/reference/parameter_types/item_link`
* :doc:`/reference/parameter_types/link`
* :doc:`/reference/parameter_types/number`
* :doc:`/reference/parameter_types/range`
* :doc:`/reference/parameter_types/text_line`
* :doc:`/reference/parameter_types/text`
* :doc:`/reference/parameter_types/url`

The following parameter types are available in integration with eZ Platform.

* :doc:`/reference/parameter_types/ez_content_type`
* :doc:`/reference/parameter_types/ez_location`
* :doc:`/reference/parameter_types/ez_tags`
