name: Docs

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'
  pull_request: ~

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install -r requirements.txt

      - run: make SPHINXOPTS=-nW html
